version: "3.9"

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: tranuser
      POSTGRES_PASSWORD: secretPassword@167
      POSTGRES_DB: transvc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432" 



  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80" 
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - backend

  transaction-api:
    build:
      context: ./tx-api
      dockerfile: Dockerfile
    container_name: transaction-api
    restart: always
    environment:
      APP_ENV: docker   
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend
