version: "3.9"

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: tranuser
      POSTGRES_PASSWORD: secretPassword@167
      POSTGRES_DB: transvc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"      # expose so laptop API can connect

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - backend
    ports:
      - "6379:6379"      # expose so laptop API can connect

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"        # external access
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - backend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: transaction-api
    restart: always
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - backend
