local:
  database:
    host: localhost
    port: 5432
    user: tranuser
    password: secretPassword@167
    name: transvc
    schema: transvc

docker:
  database:
    host: postgres     
    port: 5432
    user: tranuser
    password: secretPassword@167
    name: transvc
    schema: transvc

